using System.Collections.Generic;

namespace FlynnDW.Data.Constants
{
    public class Constants
    {
        public class AppSettings
        {
            public const string TbeRootDir = "TbeRootDir";
            public const string TbeParsedRootDir = "TbeParsedDir"; 

            public const string PosLogRootDir = "PosLogRootDir";
            public const string PosLogParsedDir = "PosLogParsedDir";
        } 
         // this dict is a key-value pair between the code and folder/table name
                // NOTE: "000" is a dummy code to give a placeholder for the folder name of "PacketHeader"
                public  static Dictionary<string, string> FileTypes = new Dictionary<string, string>()
                {
                    { "000", "PacketHeader" },  // faux code of 000 here to handle packet header
                    { "AH1", "AdjustmentHoursRecord" },
                    { "AL1", "ActualLaborHoursRecord" },
                    { "AP1", "AlternatePaymentMethodRecord" },
                    { "BS1", "BatchSettlementRecord" },
                    { "CC1", "CanadianCashRecord" },
                    { "CD1", "DepositRecord" },
                    { "CH1", "CharityCollectedRecord" },
                    { "CM0", "ComboMealSalesRecord" },
                    { "CM1", "ComboMealSalesMixRecord" },
                    { "CM2", "ComboMealSalesMixCondimentData" },
                    { "CO0", "InterStoreTransferCreditOutHeader" },
                    { "CO1", "InterStoreTransferCreditOutDetail" },
                    { "CR0", "ShiftAccountabilityCashierPerformanceData" },
                    { "CR1", "ShiftAccountabilityCashierPerformanceDropData" },
                    { "CR2", "ShiftAccountabilityCashierDropMethodData" },
                    { "CS1", "CanadianSales" },
                    { "DP1", "AlternatePaymentMethodDetailRecord" },
                    { "DR0", "RevisedDriveThruTimerSpeedofServiceHeader" },
                    { "DR1", "RevisedDriveThruTimerSpeedofServiceDetail" },
                    { "DT0", "DriveThruTimerSpeedofServiceHeader" },
                    { "DT1", "DriveThruTimerSpeedofServiceDetail" },
                    { "EH1", "EmployeesHoursRecords" },
                    { "EH2", "EmployeeHoursRecordsWithSpreadOfHoursBonus " },
                    { "EM1", "ExcessiveManualAdjustmentsRecord" },
                    { "EP1", "PolledAlternatePaymentMethodDetailRecord" },
                    { "EV1", "BackofHousetypeandTacoBellExtractGenerationVersionNumber" },
                    { "FC0", "FrontCounterSpeedofServiceHeader" },
                    { "FC1", "FrontCounterSpeedofServiceDetail" },
                    { "FR0", "RevisedFrontCounterSpeedofServiceHeader" },
                    { "FR1", "RevisedFrontCounterSpeedofServiceDetail" },
                    { "FP1", "SWEEPSEndofPeriodReportData" },
                    { "FW1", "SWEEPSEndofWeekReportData" },
                    { "GF1", "MenuItemGiveawayRecord" },
                    { "GR1", "IngredientGiveawayRecord" },
                    { "HI1", "EmployeeRecord" },
                    { "HI2", "EmployeeRecord" },
                    { "IA1", "InventoryCountRecord–Actualcost" },
                    { "IC1", "InventoryCountRecord" },
                    { "JC1", "JobCodeChangeRecord" },
                    { "LA1", "LeaveofAbsenceRecord" },
                    { "LF1", "LaborForecastRecord" },
                    { "LI0", "InterStoreTransferLoanInHeader" },
                    { "LI1", "InterStoreTransferLoanInDetail" },
                    { "LO0", "InterStoreTransferLoanOutHeader" },
                    { "LO1", "InterStoreTransferLoanOutDetail" },
                    { "LR1", "LaborForecastHoursRecord" },
                    { "LX1", "TimeEntryAdjustmentRecord" },
                    { "MB1", "MultiBrandSalesRecord" },
                    { "MS0", "CFMManagerSpecialsHeader" },
                    { "MI1", "CFMManagerSpecialsItems" },
                    { "OP1", "MiscellaneousOperationsRecord" },
                    { "OX1", "SpeedofServiceDetailRecord" },
                    { "PB0", "PFSDeliveryReceiptHeaderRecord" },
                    { "PB1", "PFSDeliveryReceiptDetailRecord" },
                    { "PC0", "CashVoucherHeaderRecord" },
                    { "PC1", "CashVoucherDetailRecord" },
                    { "PM1", "PaymentMethodRecord" },
                    { "PV0 ", "NonPFSDeliveryReceiptHeaderRecord" },
                    { "PV1", "NonPFSDeliveryReceiptDetailRecord" },
                    { "RP1", "RestaurantProfileRecord" },
                    { "RR0", "RevenueRecognitionHeaderRecord" },
                    { "RR1", "RevenueRecognitionDetailRecord" },
                    { "S11", "OffPremiseSalesTransactionRecord" },
                    { "S21", "OffPremiseSalePaymentMethodRecord" },
                    { "S31", "OffPremiseSaleItemRecord" },
                    { "SC1", "AuditReasonRecord" },
                    { "SD1", "DaypartSalesRecord" },
                    { "SF0", "ShiftAccountabilityShiftPerformanceRecord" },
                    { "SF1", "ShiftAccountabilityShiftPerformanceInventoryRecord" },
                    { "SF2", "ShiftAccountabilityDrinksPerTransactionDatabyShift" },
                    { "SF3", "ShiftAccountabilityShiftPerformanceMICDateTimeBoundaries" },
                    { "SF4", "ShiftAccountabilityShiftPerformanceMICDateTimeBoundariesWithEmployeeSSNAndYUMID " },
                    { "SF5", "ShiftAccountabilityShiftPerformanceInventoryRecord–withActualCost" },
                    { "SI0", "InterStoreTransferSaleInHeader" },
                    { "SI1", "InterStoreTransferSaleInDetail" },
                    { "SO0", "InterStoreTransferSaleOutHeader" },
                    { "SO1", "InterStoreTransferSaleOutDetail" },
                    { "SL1", "SalesbySalesType" },
                    { "SL2", "SalesandDescriptionbySalesType" },
                    { "SM1", "SalesMixRecord" },
                    { "SP0", "PromotionHeaderRecord" },
                    { "SP1", "PromotionDetailRecord" },
                    { "SR1", "NonResettableTotalsRecord" },
                    { "SS1", "NonResettableOutofSequenceRecord" },
                    { "ST1", "SalesTotalRecord" },
                    { "SU1", "RawItemUsageRecord" },
                    { "SV1", "ParRegisterRecord" },
                    { "SX1", "SalesInfoRecord" },
                    { "TA1", "TrainingAllocationRecord" },
                    { "TC1", "TCOSBonusRecord" },
                    { "TD1", "TCOSRecordbyInventoryNumber" },
                    { "TI0", "InventoryTransferInHeaderRecord" },
                    { "TI1", "InventoryTransferInDetailRecord" },
                    { "TL1", "TargetLaborRecord" },
                    { "TM1", "TimeEntryRecord" },
                    { "TO0", "InventoryTransferOutHeaderRecord" },
                    { "TO1", "InventoryTransferOutDetailRecord" },
                    { "TP1", "TrainingPersonnelRecord" },
                    { "TS1", "TrainingDataforScorecardRecord" },
                    { "TT1", "OBWTrainingDataforScorecardRecord" },
                    { "VP1", "VendorProfileRecord" },
                    { "WF1", "MenuItemWasteRecord" },
                    { "WR1", "IngredientWasteRecord" }
                };
    }
}